{
  imports = [
    ./auto-pairs.nix
    ./colorizer.nix
    ./comment-box.nix
    ./session.nix
    ./comment.nix
    ./flash.nix
    ./grapple.nix
    ./harpoon.nix
    ./hardtime.nix
    ./illuminate.nix
    ./markview.nix
    ./obsidian.nix
    ./oil.nix
    ./spectre.nix
    ./todo-comments.nix
    ./ufo.nix
    ./undotree.nix
    ./wakatime.nix
    ./whichkey.nix
    ./yaml-companion.nix
  ];
}
